language: java
jdk: oraclejdk8
install: mvn clean install -Dmaven.test.skip=true -Dmaven.javadoc.skip=true -B -V
cache:
  directories:
    - $HOME/.m2/
branches:
  only:
    - master
#before_deploy: 
#  - chmod +x ./ci.sh
#  - ./ci.sh
#deploy:
#  skip_cleanup: true
#  provider: codedeploy
#  wait-until-deployed: true
#  access_key_id: "AKIAJIBJHIJI2FGADYVQ"
#  secret_access_key:
#    secure: "Rc0BAmtud3Wk+HnDmTR1PIRkXrpTcInzDC37B88NN9SV9ejOkJaa8mK27p11JjOy35ibOLcNWvw7BUFveg5akRjT4nMkdkq0EqZ2+QiUX2G+Nc3+ks6mKW1GeApKZnYuitr6YRCPjPH37GRKhgBjoRm3M1C8sou/AACrf+UkfTRuxM/tEawK50v06YWCiZvs4+4Np5BRfLVOihiQjzJ27seK+RRmn9v1nUOP5qUJaWY0wHLE034nTk75xWj70ZK2/iiPNq+l3AerFeoTnIPXlRSyCKPHjZGZdKdthhpcnJidmNtuDZpxLFtFUEqB6bZ/M32hlhKrhZaP/9ahgMoLKm8wIYipj4of9FvO2kIBdbPBgrFHH9lgTMzbsEwac0bC83SSYD8LzG+pgCXXbwUEKTCy+J0/B2cO9JJnokVao5JKTU834OE00KxAlAmnzJ61+8zEmnIKO0uhyuRBU8jZelgCuO5PShb1HMfkwDJ4T1dgUrRxs3D7bY3PzrgHD5I5FOQ3ndyffSPqGGvrl+DlRId7aIlSHIK2mFRvnBm4zHex7F+vkHxZButeXXE1EjkMvRa1H75V8V8BI36YBnrWTqHyL4YqfUl2SENgp3ryoNc0yT0Jis+53ipUs+ljUIRnRlAKp8HjGJw7AqR0RRRmzaFYC7nDcZ1qEtye8n6E9/o="
#  bucket: "astro-app-deploy"
#  key: latest/astro-app.zip
#  application: astro-app
#  deployment_group: astro-deployment
#  on:
#    branch: master
