spring:
  datasource:
    url: ${datasource.url}
    username: ${datasource.username}
    password: ${datasource.password}
logging:
  level:
    root: info
server:
  session:
    tracking-modes: COOKIE
    timeout: 1800 #(30 minutes)
    persistent: true
    cookie:
      name: SESSIONID
      http-only: true
  use-forward-headers: true
---
spring:
  profiles: prod
  datasource:
    schema: classpath:org/springframework/session/jdbc/schema-postgresql.sql
---
spring:
  profiles: dev
  datasource:
    url: jdbc:h2:mem:umdastro
    username: sa
    password: 
    schema: classpath:org/springframework/session/jdbc/schema-h2.sql
  h2:
    console:
      enabled: true
      path: /public/h2
security:
  headers:
    frame: false
  enable-csrf: false