spring:
  datasource:
    url: ${datasource.url}
    username: ${datasource.username}
    password: ${datasource.password}
logging:
  level:
    root: info
server:
  session:
    timeout: 1800 #(30 minutes)
    persistent: true
    cookie:
      name: SESSIONID
      http-only: true