spring:
  datasource:
    url: ${datasource.url}
    username: ${datasource.username}
    password: ${datasource.password}
  jpa:
    database-platform: edu.umdearborn.astronomyapp.config.jpa.PostgreSql94RemapClobDialect
    generate-ddl: false
    hibernate:
      ddl-auto: none
  cache:
    guava:
      spec: maximumSize=500,expireAfterAccess=600s
server:
  port: ${port:8080}
  session:
    timeout: 1800 #(30 minutes)
  use-forward-headers: true
---
spring:
  profiles: db-init
  datasource:
    schema: classpath:org/springframework/session/jdbc/schema-drop-postgresql.sql,
      classpath:org/springframework/session/jdbc/schema-postgresql.sql
  jpa:
    generate-ddl: true
---
spring:
  profiles: trace
  jpa:
    properties:
      hibernate.show_sql: true
      hibernate.use_sql_comments: true
      hibernate.format_sql: true
logging:
  level:
    root: info
    edu.umdearborn.astronomyapp: debug
    org.hibernate.type: trace
