spring:
  datasource:
    url: ${datasource.url}
    username: ${datasource.username}
    password: ${datasource.password}
logging:
  level:
    root: info
server:
  port: ${port:8080}
  session:
    timeout: 1800 #(30 minutes)
  use-forward-headers: true
---
spring:
  profiles: db-init
  datasource:
    schema: classpath:org/springframework/session/jdbc/schema-drop-postgresql.sql,
      classpath:org/springframework/session/jdbc/schema-postgresql.sql
#    data: classpath:test-data-init/test-users.sql
  jpa:
    generate-ddl: true
---
spring.profiles: dev
spring:
  profiles:
    include: db-init
  datasource:
    url: jdbc:h2:mem:umdastro;MODE=PostgreSQL
#    url: jdbc:h2:~/umdastro;MODE=PostgreSQL
    username: sa
    password:
  h2:
    console:
      enabled: false
logging:
  level:
    edu.umdearborn.astronomyapp: debug
