spring:
  datasource:
    url: ${datasource.url}
    username: ${datasource.username}
    password: ${datasource.password}
logging:
  level:
    root: info
server:
  session:
    timeout: 1800 #(30 minutes)
  use-forward-headers: true
---
spring:
  profiles: prod-init
  datasource:
    schema: classpath:org/springframework/session/jdbc/schema-postgresql.sql
  jpa:
    generate-ddl: true
---
spring:
  profiles: dev
  datasource:
    url: jdbc:h2:mem:umdastro
    username: sa
    password: 
    schema: classpath:org/springframework/session/jdbc/schema-h2.sql
  h2:
    console:
      enabled: false
logging:
  level:
    edu.umdearborn.astronomyapp: debug
  