spring:
  datasource:
    url: ${datasource.url}
    username: ${datasource.username}
    password: ${datasource.password}
  jpa:
    database-platform: edu.umdearborn.astronomyapp.config.jpa.PostgreSql94RemapClobDialect
logging:
#  file: astro-app.log
  level:
    root: info
server:
  port: ${port:8080}
  session:
    timeout: 1800 #(30 minutes)
  use-forward-headers: true
---
spring:
  profiles: db-init
  datasource:
    schema: classpath:org/springframework/session/jdbc/schema-drop-postgresql.sql,
      classpath:org/springframework/session/jdbc/schema-postgresql.sql
#    data: classpath:test-data-init/test-users.sql
  jpa:
    generate-ddl: true
---
spring:
  profiles: dev
logging:
  level:
    edu.umdearborn.astronomyapp: debug
